

platform :ios, '8.0'

target 'coobjcBaseExample' do

pod 'coobjc', :path => '../../'

end

target 'coobjcBaseExampleTests' do

    pod 'coobjc', :path => '../../'

    pod 'Specta', '~> 1.0'
    pod 'Expecta',     '~> 1.0'   # expecta matchers
    pod 'OCMock',      '~> 2.2'   # OCMock
end
